version: "3"

services:
    db:
        image: mysql:8.0.23
        platform: linux/x86_64
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - "db_app:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - 3307:3306
        networks:
            - symfony
    php:
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony/
        networks:
            - symfony
    nginx:
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony/
        ports:
            - 120:80
        networks:
            - symfony
        env_file:
            - .env.nginx.local
    ngrok:
        image: ngrok/ngrok:latest
        restart: unless-stopped
        command:
            - "start"
            - "--all"
            - "--config"
            - "/etc/ngrok.yml"
        extra_hosts:
            - "test.drus:172.19.0.5"
        volumes:
            - ./ngrok.yml:/etc/ngrok.yml
        ports:
            - 4040:4040
        networks:
            - symfony
volumes:
    symfony_dockerized_app_sync:

    db_app:

networks:
    symfony:
